version: '3.4'

services:
  myapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - USE_LOCAL_CONFIG_FILE=false
      - APPCONFIG_APPID=ybhn6xi
      - APPCONFIG_ENVID=41wexz1
      - APPCONFIG_PROFILEID=znsr7i1
    ports:
      - 54436:80

  myworker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - USE_LOCAL_CONFIG_FILE=false
      - APPCONFIG_APPID=ybhn6xi
      - APPCONFIG_ENVID=41wexz1
      - APPCONFIG_PROFILEID=xw8h8b7
   